name: 'GitHub CICD'
run-name: "Testing APP"

defaults:
    run:
        shell: bash
        working-directory: ./


on:
    push:
        branches:
            - main


jobs:
    build:
        runs-on: "ubuntu-latest"
        steps:
            - name: "Install Deps"
              run: npm run dev

            - name: "Build App"
              run: npm run build
      