name: Preview
run-name: ${{ github.actor}} is Running this action

on: 
  push:
  workflow_dispatch:

jobs:
  use-reusable:
    uses: AbdulHaseeb-1/ci-templates/.github/workflows/build.yml@main
    with:
      enviorment: Production

    
  