name: Preview
run-name: ${{ github.actor}} is Running this action

on: 
  workflow_dispatch:
    inputs:
      enviorment:
        description: What Enviorment You Are In?
        required: true
        type: choice
        options:    
          - production
          - staging 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: actions/checkout/v4
      - run: echo " 😃 Starting the actoin "
  
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploying
        run: echo "I am ready to deploy"    