name: BuildFlow
run-name: build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # fetch all commits & tags


      - name: Install Deps
        run: npm install

      - name: Build Site
        run: npm run build

